return {
    cursor_color = "#ff0000",
    particles_enabled = true,
    stiffness = 0.8,
    stiffness_insert_mode = 0.7,
    trailing_stiffness = 0.7,
    trailing_stiffness_insert_mode = 0.7,
    trailing_exponent = 5,
    damping = 0.95,
    damping_insert_mode = 0.95,
    distance_stop_animating = 0.5,
    gradient_exponent = 0,
    gamma = 1,
    never_draw_over_target = true,
    hide_target_hack = true,
    particle_spread = 1,
    particles_per_second = 500,
    particles_per_length = 50,
    particle_max_lifetime = 800,
    particle_max_initial_velocity = 20,
    particle_velocity_from_cursor = 0.5,
    particle_damping = 0.15,
    particle_gravity = -50,
    min_distance_emit_particles = 0,
    legacy_computing_symbols_support = true,
    transparent_bg_fallback_color = "#303030",
}
